// Product data with real images
const products = [
  {
    id: "1",
    title: "Wireless Bluetooth Headphones - Premium Sound Quality",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&crop=center",
    rating: 4.5,
    reviews: 1234,
    category: "Electronics",
    description: "High-quality wireless headphones with active noise cancellation and 30-hour battery life",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "2",
    title: "Smart Fitness Watch - Health & Activity Tracker",
    price: 199.99,
    originalPrice: 249.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&crop=center",
    rating: 4.3,
    reviews: 856,
    category: "Electronics",
    description: "Advanced fitness tracking with heart rate monitor, GPS, and waterproof design",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "3",
    title: "Premium Coffee Maker - Programmable Brewing System",
    price: 149.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop&crop=center",
    rating: 4.7,
    reviews: 432,
    category: "Home & Garden",
    description: "Professional-grade coffee maker with programmable settings and thermal carafe",
    inStock: true,
    fastDelivery: false,
  },
  {
    id: "4",
    title: "Organic Cotton T-Shirt - Comfortable & Sustainable",
    price: 24.99,
    originalPrice: 34.99,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop&crop=center",
    rating: 4.2,
    reviews: 678,
    category: "Clothing",
    description: "100% organic cotton t-shirt available in multiple colors and sizes",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "5",
    title: "Gaming Mechanical Keyboard - RGB Backlit",
    price: 89.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=400&fit=crop&crop=center",
    rating: 4.6,
    reviews: 923,
    category: "Electronics",
    description: "Mechanical gaming keyboard with customizable RGB lighting and tactile switches",
    inStock: false,
    fastDelivery: false,
  },
  {
    id: "6",
    title: "Premium Yoga Mat - Non-Slip Exercise Mat",
    price: 39.99,
    originalPrice: 49.99,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop&crop=center",
    rating: 4.4,
    reviews: 567,
    category: "Sports",
    description: "Eco-friendly yoga mat with superior grip and cushioning, includes carrying strap",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "7",
    title: "Bestselling Fiction Novel - Award Winner",
    price: 14.99,
    originalPrice: 19.99,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop&crop=center",
    rating: 4.8,
    reviews: 2341,
    category: "Books",
    description: "Critically acclaimed fiction novel by renowned author, perfect for book clubs",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "8",
    title: "Natural Skincare Set - Complete Routine",
    price: 59.99,
    originalPrice: 79.99,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop&crop=center",
    rating: 4.5,
    reviews: 445,
    category: "Beauty",
    description: "Complete skincare routine with natural ingredients, suitable for all skin types",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "9",
    title: "Educational Building Blocks - STEM Learning Toy",
    price: 34.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center",
    rating: 4.6,
    reviews: 789,
    category: "Toys",
    description: "Creative building blocks that promote STEM learning for children aged 3-8",
    inStock: true,
    fastDelivery: false,
  },
  {
    id: "10",
    title: "Wireless Ergonomic Mouse - Long Battery Life",
    price: 29.99,
    originalPrice: 39.99,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop&crop=center",
    rating: 4.1,
    reviews: 334,
    category: "Electronics",
    description: "Ergonomic wireless mouse with precision tracking and 12-month battery life",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "11",
    title: "Designer Denim Jeans - Premium Quality",
    price: 89.99,
    originalPrice: 120.0,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop&crop=center",
    rating: 4.3,
    reviews: 567,
    category: "Clothing",
    description: "Premium denim jeans with perfect fit and sustainable manufacturing",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "12",
    title: "Indoor Plant Collection - Air Purifying Plants",
    price: 45.99,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=400&fit=crop&crop=center",
    rating: 4.7,
    reviews: 223,
    category: "Home & Garden",
    description: "Beautiful collection of air-purifying indoor plants, perfect for home or office",
    inStock: true,
    fastDelivery: false,
  },
  {
    id: "13",
    title: "Professional Chef Knife Set - Japanese Steel",
    price: 129.99,
    originalPrice: 159.99,
    image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=400&h=400&fit=crop&crop=center",
    rating: 4.8,
    reviews: 892,
    category: "Home & Garden",
    description: "Professional-grade knife set made from Japanese steel with ergonomic handles",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "14",
    title: "Wireless Earbuds - True Wireless Stereo",
    price: 49.99,
    originalPrice: 69.99,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&crop=center",
    rating: 4.2,
    reviews: 1156,
    category: "Electronics",
    description: "True wireless earbuds with charging case and superior sound quality",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "15",
    title: "Running Shoes - Lightweight & Breathable",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&crop=center",
    rating: 4.4,
    reviews: 743,
    category: "Sports",
    description: "Lightweight running shoes with breathable mesh and responsive cushioning",
    inStock: true,
    fastDelivery: true,
  },
  {
    id: "16",
    title: "Cookbook Collection - International Cuisine",
    price: 29.99,
    originalPrice: 39.99,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=400&fit=crop&crop=center",
    rating: 4.6,
    reviews: 456,
    category: "Books",
    description: "Comprehensive cookbook featuring recipes from around the world",
    inStock: true,
    fastDelivery: false,
  },
]

// Categories array
const categories = ["Electronics", "Clothing", "Books", "Home & Garden", "Sports", "Beauty", "Toys"]

// Utility functions
function formatPrice(price) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(price)
}

function calculateDiscount(originalPrice, currentPrice) {
  if (!originalPrice) return 0
  return Math.round(((originalPrice - currentPrice) / originalPrice) * 100)
}

// Make data globally available
window.products = products
window.categories = categories
window.formatPrice = formatPrice
window.calculateDiscount = calculateDiscount
